# available blueprints
blueprints = {}

blueprints["shortsword"] = {"chinese_name": "侍從之劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["longsword"] = {"chinese_name": "騎士之劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["broadsword"] = {"chinese_name": "羅馬短劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grottosword"] = {"chinese_name": "喬木之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["zweihander"] = {"chinese_name": "雙手劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cutlass"] = {"chinese_name": "護手彎刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["rapier"] = {"chinese_name": "護手刺劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["herosword"] = {"chinese_name": "英雄之劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["candysword"] = {"chinese_name": "巧克力之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["katana"] = {"chinese_name": "武士刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallsword"] = {"chinese_name": "鋸齒五指劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["scimitar"] = {"chinese_name": "王者之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cyclopssword"] = {"chinese_name": "時空符文之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["celesteelblade"] = {"chinese_name": "天鋼之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ruinssword"] = {"chinese_name": "達摩克利斯劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldsword"] = {"chinese_name": "豪華水晶鋸劍", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["newyearsword"] = {"chinese_name": "結晶禮劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["falchion"] = {"chinese_name": "秘銀利刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["poloniacutlass"] = {"chinese_name": "航海者之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["canesword"] = {"chinese_name": "紳士之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cleaver"] = {"chinese_name": "超大砍刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["templesword"] = {"chinese_name": "卡拉德波加", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dragonsword"] = {"chinese_name": "龍刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunarsword"] = {"chinese_name": "虎之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["vorpalsword"] = {"chinese_name": "漩渦劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["victoriansword"] = {"chinese_name": "優雅長劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["moonsword"] = {"chinese_name": "月讀", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12sword"] = {"chinese_name": "王者之劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shoprsword"] = {"chinese_name": "泰坦之劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldsword2"] = {"chinese_name": "富饒烙印", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["musketeersword"] = {"chinese_name": "達太安之劍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["pumpkinsword"] = {"chinese_name": "蔑視之刺", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13sword"] = {"chinese_name": "德金火祭", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["spacesword"] = {"chinese_name": "電漿軍刀", "crafting_upgrade": 0, "ascension_upgrade": 0}

blueprints["boysaxe"] = {"chinese_name": "伐木斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hatchet"] = {"chinese_name": "短斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["doublebitted"] = {"chinese_name": "鐵斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["exploreraxe"] = {"chinese_name": "探索者斧頭", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["halberd"] = {"chinese_name": "半月斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grottoaxe"] = {"chinese_name": "熔融槍斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["epicaxe"] = {"chinese_name": "拆卸者的鶴嘴鋤", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["tomahawk"] = {"chinese_name": "印地安戰斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["starteraxe"] = {"chinese_name": "手斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["snowaxe"] = {"chinese_name": "冷鐵斧頭", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["battleaxe"] = {"chinese_name": "戰斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["birdaxe"] = {"chinese_name": "猛禽掠奪", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["steelaxe"] = {"chinese_name": "矮人巨斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pyramidaxe"] = {"chinese_name": "切石者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["raideraxe"] = {"chinese_name": "掠奪者斧頭", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lunaraxe"] = {"chinese_name": "錢斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["executioner"] = {"chinese_name": "执行者", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["castleaxe"] = {"chinese_name": "煉獄", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cincoaxe2020"] = {"chinese_name": "第五之斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["crescentaxe"] = {"chinese_name": "月蝕", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["templeaxe"] = {"chinese_name": "塔拉泰藍尼斯", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldaxe"] = {"chinese_name": "富饒大斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["coupleaxe"] = {"chinese_name": "科迪亞克砍刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["manticoreaxe"] = {"chinese_name": "螳螂殺手", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beeaxe"] = {"chinese_name": "蜂蠟斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallaxe"] = {"chinese_name": "菇菇毀滅", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["aegiraxe"] = {"chinese_name": "霜巨人剋星", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12axe"] = {"chinese_name": "征服彎斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["chessaxe"] = {"chinese_name": "瑪瑙國王斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentineaxe"] = {"chinese_name": "戀人的爭吵", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dinoaxe"] = {"chinese_name": "頂點血斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13axe"] = {"chinese_name": "永恆邊界", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["firecrabaxe"] = {"chinese_name": "脫殼蟹鉗", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["kitchenknife"] = {"chinese_name": "小刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["forestdagger"] = {"chinese_name": "冰鎬", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["dagger"] = {"chinese_name": "敏捷之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["kunai"] = {"chinese_name": "苦無", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["switchblade"] = {"chinese_name": "隱形刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["butterflyknife"] = {"chinese_name": "蝴蝶刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["schooldagger2020"] = {"chinese_name": "博學者向量", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["kris"] = {"chinese_name": "儀式匕首", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_boomerang"] = {"chinese_name": "蘇卡的迴旋鏢", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["yamidagger"] = {"chinese_name": "忍者坦托", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["dirk"] = {"chinese_name": "國王守護者", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lunardagger"] = {"chinese_name": "雲行者查克拉姆", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beachdagger"] = {"chinese_name": "風味雪糕", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["guttingknife"] = {"chinese_name": "魚販", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["junimaydagger"] = {"chinese_name": "茱妮波的鏟子", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["trolltooth"] = {"chinese_name": "巨魔牙 ", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ruinsdagger"] = {"chinese_name": "利維亞尖牙", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["misericordia"] = {"chinese_name": "慈悲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["sultandagger"] = {"chinese_name": "蘇丹匕首", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["golddagger"] = {"chinese_name": "豪華長匕", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["katar"] = {"chinese_name": "儀式爪刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["templedagger"] = {"chinese_name": "夢魘魔刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["siadagger"] = {"chinese_name": "天鵝之刃", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["stpatrickdagger"] = {"chinese_name": "幸運打擊", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["heartseeker"] = {"chinese_name": "尋心者", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["peakdagger"] = {"chinese_name": "最後吐息", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["halloweendagger"] = {"chinese_name": "夜翼箭", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_kyoshifan"] = {"chinese_name": "京島戰士扇子", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["wiccandagger"] = {"chinese_name": "威卡匕首", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12dagger"] = {"chinese_name": "第六大罪", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["golddagger2"] = {"chinese_name": "富饒石祭刀", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mushroomdagger"] = {"chinese_name": "天鋼手指虎", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunardagger2"] = {"chinese_name": "皇后鐵扇", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13dagger"] = {"chinese_name": "夜曲", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["club"] = {"chinese_name": "短棒", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["spikedclub"] = {"chinese_name": "狼牙短棒", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["forestmace"] = {"chinese_name": "黑木樹枝", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hammer"] = {"chinese_name": "戰錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["libertymace"] = {"chinese_name": "自由釘頭錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["morningstar"] = {"chinese_name": "流星錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["summermace"] = {"chinese_name": "充氣槌", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["heavymace"] = {"chinese_name": "凸緣釘錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["newyearmace"] = {"chinese_name": "年始流星錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ancienthammer"] = {"chinese_name": "破顱者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["troblinmace"] = {"chinese_name": "茶包林棍棒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["midnightstar"] = {"chinese_name": "昏星錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pyramidmace"] = {"chinese_name": "流星錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["arcademace"] = {"chinese_name": "按鈕狂打鎚", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["powderkeg"] = {"chinese_name": "火藥桶", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pumpkinmace"] = {"chinese_name": "敲製南瓜燈", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["candyhammer"] = {"chinese_name": "薄荷木槌", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["tenderizer"] = {"chinese_name": "鬆肉器", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["smithhammer"] = {"chinese_name": "華勒斯大鎚", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["freedommace"] = {"chinese_name": "條紋星錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["nautilus"] = {"chinese_name": "鸚鵡螺", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldhammer"] = {"chinese_name": "富饒之錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mundrahammer"] = {"chinese_name": "穆德拉搗碎棒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["emeraldhammer"] = {"chinese_name": "瑟銀錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["peakhammer"] = {"chinese_name": "陽光衝擊槍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["naturehammer"] = {"chinese_name": "蓋亞之槌", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_mace"] = {"chinese_name": "蘇卡的棍棒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12mace"] = {"chinese_name": "雷神之錘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["eastermace"] = {"chinese_name": "蛋殼粉碎者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasmace"] = {"chinese_name": "聖誕釘頭錘快樂", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13mace"] = {"chinese_name": "峭壁守護者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["musicmace"] = {"chinese_name": "猛擊", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["platinummace"] = {"chinese_name": "白金槌", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["woodspear"] = {"chinese_name": "標槍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ironspear"] = {"chinese_name": "獵矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["bladedspear"] = {"chinese_name": "戰矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["pitchfork"] = {"chinese_name": "堅固的乾草叉", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ranseur"] = {"chinese_name": "钂鈀", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["trident"] = {"chinese_name": "三叉戟", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["easterspear"] = {"chinese_name": "兔兔長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["heavenlyhalberd"] = {"chinese_name": "戰爭大師戟", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pike"] = {"chinese_name": "歐洲長戟", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["desertspear"] = {"chinese_name": "特里頓長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["celticspear"] = {"chinese_name": "庫楚蘭的長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["partisan"] = {"chinese_name": "贵宾戟", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["yetispear"] = {"chinese_name": "雙輪標槍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["africanspear"] = {"chinese_name": "戰士鐵槍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["championlance"] = {"chinese_name": "鬥士長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallspear"] = {"chinese_name": "落日長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["wyvernglaive"] = {"chinese_name": "雙足龍闊矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["sylvanspear"] = {"chinese_name": "獠牙長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldspear"] = {"chinese_name": "豪華矛", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["stellarspear"] = {"chinese_name": "星辰花", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["templespear"] = {"chinese_name": "朗基努斯", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["thanksgivingspear"] = {"chinese_name": "伯班大師戟", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["feyspear"] = {"chinese_name": "巨鱷的禮物", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["circusspear"] = {"chinese_name": "小丑喬斯特", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasspear"] = {"chinese_name": "聖善夜長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12spear"] = {"chinese_name": "天堂之怒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["airshipspear"] = {"chinese_name": "螺旋槳長矛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beachspear"] = {"chinese_name": "監獄陽傘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldspear2"] = {"chinese_name": "富饒之戟", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13spear"] = {"chinese_name": "黑化半月斧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["riftspear"] = {"chinese_name": "激流", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["inuitspear"] = {"chinese_name": "硬派卡基瓦克", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["shortbow"] = {"chinese_name": "訓練弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["forestbow"] = {"chinese_name": "順風弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["longbow"] = {"chinese_name": "榆木弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hunterbow"] = {"chinese_name": "直拉弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["siabow"] = {"chinese_name": "大豎琴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["strikerbow"] = {"chinese_name": "複合弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mundrabow"] = {"chinese_name": "穆德拉角弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["spikedbow"] = {"chinese_name": "鹰眼弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["halloweenbow"] = {"chinese_name": "萬聖垂柳", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["wingedbow"] = {"chinese_name": "翅羽弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["desertbow"] = {"chinese_name": "大咬鵑翼", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["compositebow"] = {"chinese_name": "阿拉伯風", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["westernbow"] = {"chinese_name": "神槍手弩槍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["yumi"] = {"chinese_name": "由美", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentinebow"] = {"chinese_name": "邱比特之弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["bramblebane"] = {"chinese_name": "荊棘弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallbow"] = {"chinese_name": "楓木強風", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["twinstrand"] = {"chinese_name": "雙子星打擊", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasbow"] = {"chinese_name": "快樂的遊俠", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["stormrend"] = {"chinese_name": "雷暴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldbow"] = {"chinese_name": "富饒長弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cincobow"] = {"chinese_name": "皮納塔獵人", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["newyearbow"] = {"chinese_name": "晨星", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["frogbow"] = {"chinese_name": "枝鍛弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12bow"] = {"chinese_name": "奧林帕斯", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["arcadebow"] = {"chinese_name": "威力彈射弓", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["thanksgivingbow"] = {"chinese_name": "菁英尋路者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13bow"] = {"chinese_name": "偉大君主", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["riftbow"] = {"chinese_name": "地繫之翼", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["blossombow"] = {"chinese_name": "神代櫻", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["woodbranch"] = {"chinese_name": "雕刻過的樹枝", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cane"] = {"chinese_name": "結實手杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["oakstaff"] = {"chinese_name": "橡木法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lilustaff"] = {"chinese_name": "貓頭鷹棲木", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldstaff"] = {"chinese_name": "豪華杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["bo"] = {"chinese_name": "棒形法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["starterstaff"] = {"chinese_name": "學徒法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scepter"] = {"chinese_name": "玉之權杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["swampstaff"] = {"chinese_name": "琥珀法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["wiccanstaff"] = {"chinese_name": "威卡長柄掃帚", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["wizardstaff"] = {"chinese_name": "巫師法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["leafstaff"] = {"chinese_name": "四季法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["celestialrod"] = {"chinese_name": "天宇法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mundrastaff"] = {"chinese_name": "穆德拉權杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["imperialaquila"] = {"chinese_name": "贵宾天鷹座", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ruinsstaff"] = {"chinese_name": "鳳凰法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["musicstaff"] = {"chinese_name": "笛聲杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["transcendance"] = {"chinese_name": "超體驗法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["castlestaff"] = {"chinese_name": "潮汐使者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lemonstaff"] = {"chinese_name": "滋味權杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["conflux"] = {"chinese_name": "撒拉弗", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasstaff"] = {"chinese_name": "歡樂法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["penumbra"] = {"chinese_name": "半影", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["yetistaff"] = {"chinese_name": "冰雪女王權杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentinestaff"] = {"chinese_name": "攫心者法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12staff"] = {"chinese_name": "索利姆努爾權杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldstaff2"] = {"chinese_name": "富饒法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["hemmadonstaff"] = {"chinese_name": "捆魂法杖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["anubisstaff"] = {"chinese_name": "法老的生命", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13staff"] = {"chinese_name": "喜上雲端", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["riftstaff"] = {"chinese_name": "重力控制杖", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["collectionstaff"] = {"chinese_name": "永恆智慧權杖", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["antidote"] = {"chinese_name": "薄荷葉", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grass"] = {"chinese_name": "甜草", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["powder"] = {"chinese_name": "月亮粉", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasflower"] = {"chinese_name": "神奇槲寄生", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["healingsalve"] = {"chinese_name": "治癒軟膏", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["thanksgivingherb"] = {"chinese_name": "放久的燕麥", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["silverthistle"] = {"chinese_name": "銀薊", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["harvest"] = {"chinese_name": "豐收", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["thanksgivingherb2"] = {"chinese_name": "火石玉米捆", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["bloodvine"] = {"chinese_name": "赤藤", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["bouquet"] = {"chinese_name": "香氛花束", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mushroomherb"] = {"chinese_name": "小小仙人掌", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["mandragoraroot"] = {"chinese_name": "曼德拉草根", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentineherb"] = {"chinese_name": "不屈玫瑰", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["wolfsbane"] = {"chinese_name": "野狼禍根", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ruinsherb"] = {"chinese_name": "霧峰綻放", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["yggdrasilbranch"] = {"chinese_name": "世界樹樹枝", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldenclover"] = {"chinese_name": "最幸運三葉草", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldherb"] = {"chinese_name": "豪華藥物", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["wyrmblood"] = {"chinese_name": "龍血軟膏", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["couplebouquet"] = {"chinese_name": "狂野橡樹玫瑰", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["eldritchtendrils"] = {"chinese_name": "鬼藤叢", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["peakherbs"] = {"chinese_name": "淒涼之根", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["circusherb"] = {"chinese_name": "氣泡水驚喜", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["candyherb"] = {"chinese_name": "超級點心包", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12herb"] = {"chinese_name": "賢者之石", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["blossomherb"] = {"chinese_name": "櫻花特調", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldherb2"] = {"chinese_name": "富饒湯藥", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fruitherb"] = {"chinese_name": "高級名牌果醬", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13herb"] = {"chinese_name": "虛空綻放根", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["musicherb"] = {"chinese_name": "調音管膏", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dreamherb"] = {"chinese_name": "沙人小包", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["tea"] = {"chinese_name": "溫茶", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["smallhealthpotion"] = {"chinese_name": "治癒藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["smallmanapotion"] = {"chinese_name": "魔法藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scienceexperiment"] = {"chinese_name": "科學專案", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["healthpotion"] = {"chinese_name": "大型治癒藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["victorianpotion"] = {"chinese_name": "優雅茶組", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["magicpotion"] = {"chinese_name": "大型魔法藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shoprpotion"] = {"chinese_name": "泰坦藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["poloniapotion"] = {"chinese_name": "老水手藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["largehealthpotion"] = {"chinese_name": "鳳凰補藥", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cincopotion"] = {"chinese_name": "熱情格蘭尼達", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["vialofrenewal"] = {"chinese_name": "恢復藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pyramidpotion"] = {"chinese_name": "瓶裝快活", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["epicpotion"] = {"chinese_name": "起泡狂飲瓶", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["purplebomb"] = {"chinese_name": "紫色炸彈", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["pumpkinpotion"] = {"chinese_name": "葫蘆靈藥", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["nayapotion"] = {"chinese_name": "娜亞特製藥水", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cincopotion2"] = {"chinese_name": "特殊調味辣醬", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["soulfireextract"] = {"chinese_name": "魂火萃取物", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lemonpotion"] = {"chinese_name": "刺鼻湯藥", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["carpenterpotion"] = {"chinese_name": "橡木精華", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["gaiatonic"] = {"chinese_name": "蓋亞補藥", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["batpotion"] = {"chinese_name": "午夜油", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldpotion"] = {"chinese_name": "富饒靈藥", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["starextract"] = {"chinese_name": "壓縮的星雲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["yetipotion"] = {"chinese_name": "極光泉水", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["frogpotion"] = {"chinese_name": "花蜜壺", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12potion"] = {"chinese_name": "仙饌蜜酒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mundrapotion"] = {"chinese_name": "穆德拉的靈藥", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["volcanopotion"] = {"chinese_name": "純淨精粹", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beachpotion"] = {"chinese_name": "至高防曬", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["maplepotion"] = {"chinese_name": "楓糖聖杯", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13potion"] = {"chinese_name": "征服者之血", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["arcadepotion"] = {"chinese_name": "基礎藥水包", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["scrolloffire"] = {"chinese_name": "火花卷軸", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["forestscroll"] = {"chinese_name": "淨化卷軸", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scrollofthunder"] = {"chinese_name": "護甲卷軸", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scrollofprotection"] = {"chinese_name": "風暴卷軸", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["songofvalor"] = {"chinese_name": "英勇之歌", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["correspondence"] = {"chinese_name": "信件", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scrollofice"] = {"chinese_name": "怪物手冊", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["swampscroll"] = {"chinese_name": "夜之寶典", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["tomeofknowledge"] = {"chinese_name": "知識寶典", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scrollofinvisibility"] = {"chinese_name": "秘密寶典", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmascroll"] = {"chinese_name": "壞小孩/乖小孩清單", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["scrolloflevitation"] = {"chinese_name": "八卦板", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fireworksscroll"] = {"chinese_name": "煙火捆", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["unicornscroll"] = {"chinese_name": "獨角獸的故事", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["tarot"] = {"chinese_name": "塔羅牌組", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["vipscroll"] = {"chinese_name": "好運卷軸", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["grimoireaeternum"] = {"chinese_name": "永恆魔法書", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["waxtablet"] = {"chinese_name": "贵宾法令", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldscroll"] = {"chinese_name": "豪華石板", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["celestialscroll"] = {"chinese_name": "祖傳地圖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["priestbook"] = {"chinese_name": "禱告書", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["batscroll"] = {"chinese_name": "夜之詛咒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["celticscroll"] = {"chinese_name": "德魯伊·格里莫瓦", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["angelscroll"] = {"chinese_name": "天鋼合唱團", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["peakscroll"] = {"chinese_name": "鳳凰頌", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["freedomscroll"] = {"chinese_name": "封住的宣言", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunarscroll"] = {"chinese_name": "老虎君王令", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["allknowledge"] = {"chinese_name": "全知寶典", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12scroll"] = {"chinese_name": "困獸卷軸", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["anubisscroll"] = {"chinese_name": "法老的契約", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["newyearscroll"] = {"chinese_name": "失落星圖", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentinescroll"] = {"chinese_name": "愛情宣言", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldscroll2"] = {"chinese_name": "富饒咒語", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13scroll"] = {"chinese_name": "潘多拉魔盒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["riftscroll"] = {"chinese_name": "被封印的颶風", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["cuirass"] = {"chinese_name": "胸鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ringmail"] = {"chinese_name": "鐵鎖甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scalemail"] = {"chinese_name": "鱗甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["chainmail"] = {"chinese_name": "鎖子甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["breastplate"] = {"chinese_name": "騎士胸鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["swampheavyarmor"] = {"chinese_name": "儀式胸鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["centurionarmor"] = {"chinese_name": "百夫長護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["halfplate"] = {"chinese_name": "聖騎士板條甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["pumpkinheavyarmor"] = {"chinese_name": "棘刺男爵護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beeheavyarmor"] = {"chinese_name": "蜂巢守衛板甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ronindo"] = {"chinese_name": "武士道", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pyramidheavyarmor"] = {"chinese_name": "深海社", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_heavyarmor"] = {"chinese_name": "京島戰士護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunararmor"] = {"chinese_name": "戰爭大師板甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["generalplate"] = {"chinese_name": "將軍板條甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["oktoberfestplate"] = {"chinese_name": "雇傭步兵板條甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasheavyarmor"] = {"chinese_name": "聖誕老人守衛板甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["berserkerarmor"] = {"chinese_name": "狂戰士護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["castleheavyarmor"] = {"chinese_name": "蓋亞執行者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["freedomplate"] = {"chinese_name": "星條板條甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["juggernaut"] = {"chinese_name": "主宰堡壘", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["templearmor"] = {"chinese_name": "琥珀城塞", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldplate"] = {"chinese_name": "富饒胸鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["celticheavyarmor"] = {"chinese_name": "愛爾蘭鎧甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["celestialplate"] = {"chinese_name": "天鋼鎧甲", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["dogheavyarmor"] = {"chinese_name": "犬科板條甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_fireplate"] = {"chinese_name": "烈火王國護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12heavyarmor"] = {"chinese_name": "朱紅守衛重甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallheavyarmor"] = {"chinese_name": "鬼浪人護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["darkknightheavyarmor"] = {"chinese_name": "暴君板甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cyclopsheavyarmor"] = {"chinese_name": "遊蕩武士的板甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13heavyarmor"] = {"chinese_name": "野火護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["riftheavyarmor"] = {"chinese_name": "熔岩核心板甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shoprheavyarmor"] = {"chinese_name": "泰坦板甲", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["leatherarmor"] = {"chinese_name": "皮甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["padded"] = {"chinese_name": "軟鎧甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["doublet"] = {"chinese_name": "緊身上衣", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["studded"] = {"chinese_name": "釘飾護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["winterarmor"] = {"chinese_name": "暴雪護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hide"] = {"chinese_name": "獸皮護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mundraarmor"] = {"chinese_name": "穆德拉戰袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["airshiparmor"] = {"chinese_name": "空中海盜服裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["savagearmor"] = {"chinese_name": "野蠻之裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["desertmediumarmor"] = {"chinese_name": "林間守衛護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pumpkinarmor"] = {"chinese_name": "南瓜護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ninjagarb"] = {"chinese_name": "忍者裝束", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["batarmor"] = {"chinese_name": "夜翼斗篷", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["windrunnerarmor"] = {"chinese_name": "風行者護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_armor"] = {"chinese_name": "蘇卡的服裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["dragonarmor"] = {"chinese_name": "龍皮護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["smithapron"] = {"chinese_name": "鐵匠裝束", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["captainarmor"] = {"chinese_name": "海盜斗篷", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["siaarmor"] = {"chinese_name": "天鵝之服", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lunarmedarmor"] = {"chinese_name": "雲行者護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["jackalopearmor"] = {"chinese_name": "長生教霸主裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldroguearmor"] = {"chinese_name": "鱗甲護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["troblinarmor"] = {"chinese_name": "巴克貝的護甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["catarmor"] = {"chinese_name": "貓貓小偷服裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12mediumarmor"] = {"chinese_name": "黎明盜賊制服", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["volcanomedarmor"] = {"chinese_name": "失落者斗篷", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cincomedarmor"] = {"chinese_name": "拉風雨披", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["westernarmor"] = {"chinese_name": "亡命之徒服裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13mediumarmor"] = {"chinese_name": "狂獵皮革", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dreammediumarmor"] = {"chinese_name": "夢神裝束", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["tunic"] = {"chinese_name": "布衫", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["robe"] = {"chinese_name": "黑袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["druidic"] = {"chinese_name": "德魯伊之袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["disciplerobe"] = {"chinese_name": "學徒之袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["scholartunic"] = {"chinese_name": "學者長袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["exploreroutfit"] = {"chinese_name": "探索者服裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["tailorarmor"] = {"chinese_name": "裁縫斗篷", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["witchrobe"] = {"chinese_name": "魔法少女服裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["desertlightarmor"] = {"chinese_name": "貞女華服", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["wizardrobe"] = {"chinese_name": "巫師裝束", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["midnightapparel"] = {"chinese_name": "午夜服飾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_robe"] = {"chinese_name": "安的袍裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shamanvestment"] = {"chinese_name": "薩滿袍服", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentinerobe"] = {"chinese_name": "邱比特長袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldvestments"] = {"chinese_name": "豪華裝束", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["astravestimenta"] = {"chinese_name": "星雲戰裝", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["easterarmor2020"] = {"chinese_name": "奧斯塔拉背心", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["arabiantunic"] = {"chinese_name": "沙漠外衣", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["majesticraiments"] = {"chinese_name": "萬象華服", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["indiadayarmor"] = {"chinese_name": "共和之服", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["djinnrobes"] = {"chinese_name": "德金長袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["moonrobes"] = {"chinese_name": "月光和服", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunarrobe"] = {"chinese_name": "老虎君王袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12robe"] = {"chinese_name": "大主教長袍", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["hemmadonrobe"] = {"chinese_name": "捆魂禮服", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldrobe2"] = {"chinese_name": "富饒袍服", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["volcanorobe"] = {"chinese_name": "太古原初裝束", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["unicornrobe"] = {"chinese_name": "冰雪女王絲綢", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["t13robe"] = {"chinese_name": "虛空教堂袍裝", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["ironcap"] = {"chinese_name": "結實帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["helmet"] = {"chinese_name": "戰士頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["horned"] = {"chinese_name": "有角頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["vikinghelm"] = {"chinese_name": "掠奪者頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["knighthelm"] = {"chinese_name": "騎士護面", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["swamphelm"] = {"chinese_name": "深海之舵", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["eaglecowl"] = {"chinese_name": "天鷹頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dinohelm"] = {"chinese_name": "暴龍巨咬", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["paladinhelm"] = {"chinese_name": "聖騎士頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["couplehelmet"] = {"chinese_name": "科迪亞克頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_firehelm"] = {"chinese_name": "烈火王國頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["darkknighthelm"] = {"chinese_name": "暴政王冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["kabuto"] = {"chinese_name": "武士頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["gladiatorhelm"] = {"chinese_name": "角鬥士頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beachhelm"] = {"chinese_name": "沙堡護具", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shoprhelm"] = {"chinese_name": "泰坦頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["generalheaume"] = {"chinese_name": "將軍護面", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ruinshelm"] = {"chinese_name": "十字軍頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunarhelmet"] = {"chinese_name": "戰爭大師頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["berserkerhelm"] = {"chinese_name": "狂戰士頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["centurionhelmet"] = {"chinese_name": "百夫長頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["juggernauthelm"] = {"chinese_name": "主宰熔爐", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["thanksgivinghelmet"] = {"chinese_name": "咯咯王頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldhelmet"] = {"chinese_name": "富饒護面", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["celestialhelm"] = {"chinese_name": "天鋼護面", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["doghelm"] = {"chinese_name": "犬科頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentinehelm"] = {"chinese_name": "邱比特護面", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12helm"] = {"chinese_name": "朱紅守衛頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["chesshelm"] = {"chinese_name": "瑪瑙國王頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["pumpkinhelm"] = {"chinese_name": "棘刺男爵頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13helm"] = {"chinese_name": "野火凝視", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["blossomhelm"] = {"chinese_name": "大將軍頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["platinumhelm"] = {"chinese_name": "白金頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["leathercap"] = {"chinese_name": "皮革帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["forestroguehat"] = {"chinese_name": "檐篷帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hat"] = {"chinese_name": "禮帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["featheredhat"] = {"chinese_name": "羽毛禮帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["tricorn"] = {"chinese_name": "三角帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hood"] = {"chinese_name": "絲綢頭套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasroguehat"] = {"chinese_name": "聖誕老人的精靈帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["anubisroguehat"] = {"chinese_name": "法老內梅斯頭巾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["piratehat"] = {"chinese_name": "海盜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentinehat"] = {"chinese_name": "愛意帽子", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["nightcowl"] = {"chinese_name": "夜兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pyramidroguehat"] = {"chinese_name": "游牧者面紗", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["farmerhood"] = {"chinese_name": "收割工的兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["windrunnerhat"] = {"chinese_name": "風行者帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["atlab_spiritmask"] = {"chinese_name": "藍靈面具", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["musketeerroguehat"] = {"chinese_name": "火槍手帽子", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dragonhat"] = {"chinese_name": "龍面罩", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["castleroguehat"] = {"chinese_name": "風暴龍面具", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["oktoberhat"] = {"chinese_name": "蒂羅爾高帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["captainhat"] = {"chinese_name": "海盜三角帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["indiadayhat"] = {"chinese_name": "共和頭巾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["jackalopehat"] = {"chinese_name": "長生兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["peakroguehat"] = {"chinese_name": "深淵兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cincoroguehat"] = {"chinese_name": "俠客墨西哥帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["catroguehat"] = {"chinese_name": "貓貓小偷兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldroguehat"] = {"chinese_name": "富饒頭盔", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12roguehat"] = {"chinese_name": "黎明盜賊兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["easterroguehat"] = {"chinese_name": "兔兔舞會面具", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["airshiproguehat"] = {"chinese_name": "尋龍者護目鏡", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["fallroguehat"] = {"chinese_name": "狐靈面具", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["t13roguehat"] = {"chinese_name": "狂獵頭顱", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["inuitroguehat"] = {"chinese_name": "防雪鏡帽兜", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["leathercone"] = {"chinese_name": "縫製錐帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["blackcowl"] = {"chinese_name": "黑色兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["laurels"] = {"chinese_name": "德魯伊桂冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["startertiara"] = {"chinese_name": "學徒頭冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["circlet"] = {"chinese_name": "青銅環飾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["wizardcone"] = {"chinese_name": "巫師帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["swamphat"] = {"chinese_name": "四風帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["bunnyhat"] = {"chinese_name": "奥斯特拉帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["witchhat"] = {"chinese_name": "魔法少女帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["frogmagehat"] = {"chinese_name": "防水浮葉帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["liluhat"] = {"chinese_name": "貓頭鷹兜帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["midnighthat"] = {"chinese_name": "戰術家帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["summonerhat"] = {"chinese_name": "召喚師帽子", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["chessmagehat"] = {"chinese_name": "象牙后冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shamanhat"] = {"chinese_name": "薩滿帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldhat"] = {"chinese_name": "豪華頭飾", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["astralhat"] = {"chinese_name": "星雲帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["plaguemask"] = {"chinese_name": "烏鴉面具", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["schoolhat2020"] = {"chinese_name": "咒語防護帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["tiara"] = {"chinese_name": "蛋白石王冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["bathat"] = {"chinese_name": "夜之王冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["djinnhat"] = {"chinese_name": "德金面紗", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["victorianmagehat"] = {"chinese_name": "優雅禮帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["snowmagehat"] = {"chinese_name": "冰雪女王的夏季帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12magehat"] = {"chinese_name": "大主教法冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["blossommagehat"] = {"chinese_name": "櫻花烏帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldhat2"] = {"chinese_name": "富饒頭飾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["volcanomagehat"] = {"chinese_name": "鳳凰飾冠", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunarmagehat"] = {"chinese_name": "皇后髮簪", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13magehat"] = {"chinese_name": "虛空教堂帽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["riftmagehat"] = {"chinese_name": "極樂光暈", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beachmagehat"] = {"chinese_name": "潮水頭冠", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["ironbracers"] = {"chinese_name": "鐵護腕", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lightgauntlets"] = {"chinese_name": "板條護手", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["gauntlets"] = {"chinese_name": "戰士護手", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["demigauntlets"] = {"chinese_name": "神魔護手", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pumpkingauntlets"] = {"chinese_name": "南瓜臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["knightgauntlets"] = {"chinese_name": "騎士臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasgauntlets"] = {"chinese_name": "聖誕老人守衛臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cincogauntlets"] = {"chinese_name": "第五之手", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["paladingauntlets"] = {"chinese_name": "聖騎士臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["desertgauntlets"] = {"chinese_name": "日握臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["oktoberfestgauntlets"] = {"chinese_name": "雇傭步兵臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["kote"] = {"chinese_name": "武士籠手", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["indiadaygauntlets"] = {"chinese_name": "共和臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fruitgauntlets"] = {"chinese_name": "水果臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["generalgauntlets"] = {"chinese_name": "將軍臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["berserkergauntlets"] = {"chinese_name": "狂戰士臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldgauntlets"] = {"chinese_name": "豪華護手", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["juggernautgauntlets"] = {"chinese_name": "主宰鐵爪", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["wintergauntlets"] = {"chinese_name": "凜冬之觸", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["celestialgauntlets"] = {"chinese_name": "天鋼臂鎧", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["naturegauntlets"] = {"chinese_name": "蓋亞之握", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallgauntlets"] = {"chinese_name": "先鋒護手", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["aegirgauntlets"] = {"chinese_name": "侍衛臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["t12gauntlets"] = {"chinese_name": "朱紅守衛之力", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["mushroomgauntlets"] = {"chinese_name": "惡棍的耳光拳套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldgauntlets2"] = {"chinese_name": "富饒龍拳", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["darkknightgauntlets"] = {"chinese_name": "暴君之拳", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13gauntlets"] = {"chinese_name": "野火臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["arcadegauntlets"] = {"chinese_name": "力量臂鎧", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["leathergloves"] = {"chinese_name": "皮手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["bracers"] = {"chinese_name": "腕甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["thiefgloves"] = {"chinese_name": "盜賊的手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grottogloves"] = {"chinese_name": "敏捷露指手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["patchworkgloves"] = {"chinese_name": "貼片皮革", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["studdedleathergloves"] = {"chinese_name": "釘飾手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunargloves"] = {"chinese_name": "帝王手鐲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["vambraces"] = {"chinese_name": "精靈噬血腕甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["eastergloves2020"] = {"chinese_name": "奧斯塔拉手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["savagegloves"] = {"chinese_name": "野蠻之爪", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["desertgloves"] = {"chinese_name": "黑色浮龍爪", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ninjagloves"] = {"chinese_name": "忍者手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["catgloves"] = {"chinese_name": "貓貓小偷爪", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["windrunnergloves"] = {"chinese_name": "風行者手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["blossomgloves"] = {"chinese_name": "櫻花腕套", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["dragongloves"] = {"chinese_name": "龍皮手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["oktobergloves"] = {"chinese_name": "山民指套", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["captaingloves"] = {"chinese_name": "海盜手套", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["vipgloves"] = {"chinese_name": "好運手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldgloves"] = {"chinese_name": "富饒握棒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["jackalopegloves"] = {"chinese_name": "長生手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["birdgloves"] = {"chinese_name": "猛禽之翼", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["halloweengloves"] = {"chinese_name": "夜翼腕甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12gloves"] = {"chinese_name": "黎明盜賊之觸", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["volcanogloves"] = {"chinese_name": "騙徒之指", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["cincogloves"] = {"chinese_name": "節奏手套", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["musketeergloves"] = {"chinese_name": "達太安手套", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["t13gloves"] = {"chinese_name": "狂獵手套", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["shinguards"] = {"chinese_name": "護脛", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["longboots"] = {"chinese_name": "長筒靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grieveboots"] = {"chinese_name": "鐵脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["heroboots"] = {"chinese_name": "英雄靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["heavyboots"] = {"chinese_name": "堅固脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["circusboots"] = {"chinese_name": "護板吱吱鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["knightboots"] = {"chinese_name": "騎士鐵鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["swampboots"] = {"chinese_name": "煤渣鞋底", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunargreaves"] = {"chinese_name": "戰爭大師靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["paladinboots"] = {"chinese_name": "聖騎士之靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dogboots"] = {"chinese_name": "犬爪", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["firecrabboots"] = {"chinese_name": "霸氣熔岩靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["haidate"] = {"chinese_name": "武士護腰", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["bfheavyboots"] = {"chinese_name": "黃玉脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["generalgreaves"] = {"chinese_name": "將軍脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["berserkerboots"] = {"chinese_name": "狂戰士戰靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldboots"] = {"chinese_name": "豪華之靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallboots"] = {"chinese_name": "先鋒脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["juggernautboots"] = {"chinese_name": "主宰脛甲", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["bunnyboots"] = {"chinese_name": "兔兔靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cincoboots"] = {"chinese_name": "第五脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["celestialboots"] = {"chinese_name": "天鋼靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["freedomboots"] = {"chinese_name": "星條脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["christmasboots"] = {"chinese_name": "聖誕老人守衛靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12boots"] = {"chinese_name": "朱紅守衛脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["volcanoboots"] = {"chinese_name": "狂熱之靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fruitboots"] = {"chinese_name": "水果靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldboots2"] = {"chinese_name": "富饒脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dinoboots"] = {"chinese_name": "暴龍巨踩", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13boots"] = {"chinese_name": "野火脛甲", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shoprboots"] = {"chinese_name": "泰坦靴", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["leatherboots"] = {"chinese_name": "皮靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["forestshoes"] = {"chinese_name": "開拓者", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["sandals"] = {"chinese_name": "夾腳拖", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["softshoes"] = {"chinese_name": "軟鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["romansandals"] = {"chinese_name": "軍團戰士涼鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["thiefshoes"] = {"chinese_name": "盜賊之鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["flowersandals"] = {"chinese_name": "持久涼鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["elvenshoes"] = {"chinese_name": "精靈之鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["moonshoes"] = {"chinese_name": "月光草鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["savageshoes"] = {"chinese_name": "野蠻履鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["blossomshoes"] = {"chinese_name": "櫻花足袋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["arabianshoes"] = {"chinese_name": "蘇丹步履", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["inuitshoes"] = {"chinese_name": "小型雪鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["ninjatabi"] = {"chinese_name": "忍者短布襪", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["batshoes"] = {"chinese_name": "夜翼鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["windrunnerboots"] = {"chinese_name": "風行者靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["ruinsshoes"] = {"chinese_name": "高山履鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dragonshoes"] = {"chinese_name": "龍皮靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["castleshoe"] = {"chinese_name": "瘟疫行者", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cincoshoes2020"] = {"chinese_name": "時尚鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["captainshoes"] = {"chinese_name": "海盜靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lunarboots"] = {"chinese_name": "雲行者步履", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["jackalopeshoes"] = {"chinese_name": "長生靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["birdshoes"] = {"chinese_name": "猛禽之爪", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldshoes"] = {"chinese_name": "富饒裹腳布", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["t12shoes"] = {"chinese_name": "黎明盜賊之履", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["westernshoes"] = {"chinese_name": "亡命之徒馬靴", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["thanksgivingshoes"] = {"chinese_name": "獵人鹿皮鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["junimayshoes"] = {"chinese_name": "仙女涼鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13shoes"] = {"chinese_name": "狂獵涼鞋", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["woodshield"] = {"chinese_name": "木盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["buckler"] = {"chinese_name": "重型圓盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["oakshield"] = {"chinese_name": "橡木盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ironshield"] = {"chinese_name": "鐵盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grottoshield"] = {"chinese_name": "奧勒姆守護", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["kiteshield"] = {"chinese_name": "尖形盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["imperialscutum"] = {"chinese_name": "贵宾長盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["argonshield"] = {"chinese_name": "守夜鬥士", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["largebuckler"] = {"chinese_name": "秘銀大圓盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["aegirshield"] = {"chinese_name": "掠奪者圓盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["natureshield"] = {"chinese_name": "蓋亞之盾", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["towershield"] = {"chinese_name": "雙足龍護衛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["fallshield"] = {"chinese_name": "先鋒圓盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ancestortotem"] = {"chinese_name": "先祖圖騰", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["zealouspavise"] = {"chinese_name": "飞人大盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["castleshield"] = {"chinese_name": "普羅米修斯盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["stpatrickshield"] = {"chinese_name": "愛爾蘭護盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["eastershield2020"] = {"chinese_name": "兔兔圓盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldshield"] = {"chinese_name": "豪華金盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["prideshield"] = {"chinese_name": "金鬃守衛", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dragonshield"] = {"chinese_name": "王者雙足龍護衛", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["paragon"] = {"chinese_name": "大鬍子帕拉岡", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["beeshield"] = {"chinese_name": "蜂巢防禦者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["snowshield"] = {"chinese_name": "晶冰盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12shield"] = {"chinese_name": "深淵神器", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["shoprshield"] = {"chinese_name": "泰坦護盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldshield2"] = {"chinese_name": "富饒圓盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["newyearshield"] = {"chinese_name": "黎明堡壘", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["africanshield"] = {"chinese_name": "依隆戈盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13shield"] = {"chinese_name": "葉綠盾", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["beachshield"] = {"chinese_name": "激進乘浪者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mundrashield"] = {"chinese_name": "穆德拉之盾", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["ironring"] = {"chinese_name": "鐵戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["doublering"] = {"chinese_name": "合金指環", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["fatring"] = {"chinese_name": "紅寶石戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grottoring"] = {"chinese_name": "翡翠戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["silverband"] = {"chinese_name": "銀腕帶", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["valentinering"] = {"chinese_name": "熱情戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["noblering"] = {"chinese_name": "貴族戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cincoring2020"] = {"chinese_name": "節奏戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["hemmadonring"] = {"chinese_name": "克勞德的意志", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["knightsignet"] = {"chinese_name": "騎士圖章戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["freedomring"] = {"chinese_name": "自由戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["lunarring"] = {"chinese_name": "錢環", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["batrachitestone"] = {"chinese_name": "綠鈣鎂橄欖石", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pyramidring"] = {"chinese_name": "靈灵石戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["chosenring"] = {"chinese_name": "天選之戒", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["sulfuritecoil"] = {"chinese_name": "硫磺石指環", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["batring"] = {"chinese_name": "吸血鬼族戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["feyring"] = {"chinese_name": "精靈戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["springflower"] = {"chinese_name": "曙花戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["schoolring2020"] = {"chinese_name": "畢業生代表戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldring"] = {"chinese_name": "豪華印記", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["borealis"] = {"chinese_name": "極光", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["templering"] = {"chinese_name": "北風石", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["winterring"] = {"chinese_name": "暴雪戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["bunnyring"] = {"chinese_name": "兔兔帶", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mysteriousring"] = {"chinese_name": "盧比肯監獄", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["candyring"] = {"chinese_name": "鬆脆手環", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["newyearring"] = {"chinese_name": "新起始之戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12ring"] = {"chinese_name": "無暇珠光", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["unicornring"] = {"chinese_name": "晶冰環", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["africanring"] = {"chinese_name": "奧貢的瑪瑙戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["maplering"] = {"chinese_name": "迷你楓糖包", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldring2"] = {"chinese_name": "富饒圖章戒指", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13ring"] = {"chinese_name": "銜尾蛇印記", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["ironamulet"] = {"chinese_name": "紀念項鍊", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["pendant"] = {"chinese_name": "玉項鍊", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["chain"] = {"chinese_name": "鐵鎖鍊", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["mundraamulet"] = {"chinese_name": "穆德拉護身符", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["sunpendant"] = {"chinese_name": "太陽項鍊", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["grottoamulet"] = {"chinese_name": "日食護身符", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["medal"] = {"chinese_name": "榮譽勳章", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["noblechain"] = {"chinese_name": "貴族之鍊", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["stpatrickmedallion"] = {"chinese_name": "幸運圓章", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["goldamulet"] = {"chinese_name": "豪華吉祥飾物", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["holysymbol"] = {"chinese_name": "神聖標誌", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["oktoberamulet"] = {"chinese_name": "便利吊墜", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["cincoamulet"] = {"chinese_name": "第五飾品", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["titaniumtorc"] = {"chinese_name": "鈦金絲項圈", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["timelocket"] = {"chinese_name": "神奇鐘錶", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dreamamulet"] = {"chinese_name": "捕夢者", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["magatama"] = {"chinese_name": "勾玉項鍊", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["dragonamulet"] = {"chinese_name": "龍魂吊墜", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["archivistglasses"] = {"chinese_name": "檔案員眼鏡", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["phylactery"] = {"chinese_name": "忘川法器", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["rudoamulet"] = {"chinese_name": "烏爾薩圖騰", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["spaceamulet"] = {"chinese_name": "口袋寵物", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["alimyriad"] = {"chinese_name": "個體聚合體", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["priestamulet"] = {"chinese_name": "弗蕾亞護符", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["vipamulet"] = {"chinese_name": "VIP護符", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["brisingamen"] = {"chinese_name": "布里希嘉曼", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["peakamulet"] = {"chinese_name": "季風之心", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["troblinamulet"] = {"chinese_name": "孤苦橡實", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["atlab_amulet"] = {"chinese_name": "吉安的護身符", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["wiccanamulet"] = {"chinese_name": "惡叢護符", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t12amulet"] = {"chinese_name": "堤塔妮亞的紀念品", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldamulet2"] = {"chinese_name": "富饒項鍊", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["arcadeamulet"] = {"chinese_name": "迷你手把", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["cyclopsamulet"] = {"chinese_name": "永恆砂漏", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["junimayamulet"] = {"chinese_name": "仙女花圈", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13amulet"] = {"chinese_name": "堤塔妮亞的錶", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["platinumamulet"] = {"chinese_name": "白金證章", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["baconeggs"] = {"chinese_name": "培根加蛋", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["baobun"] = {"chinese_name": "割包", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["spacemeal"] = {"chinese_name": "宇宙麥片", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["poutine"] = {"chinese_name": "起司肉汁薯條", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["maplemeal"] = {"chinese_name": "楓糖小屋特製早餐", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["patechinois"] = {"chinese_name": "牧羊人派", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["burger"] = {"chinese_name": "起司漢堡", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["pizza"] = {"chinese_name": "瑪格麗特披薩", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["arcademeal"] = {"chinese_name": "蔬菜補派", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ahipoke"] = {"chinese_name": "夏威夷生鮪魚蓋飯", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["newyearmeal"] = {"chinese_name": "奶油扇貝", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["sushi"] = {"chinese_name": "壽司", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["coconutcurry"] = {"chinese_name": "超辣咖哩", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["kebabs"] = {"chinese_name": "蔬菜烤串", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["ramen"] = {"chinese_name": "豪華日式拉麵", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lunarmeal"] = {"chinese_name": "清蒸石斑", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["t12meal"] = {"chinese_name": "轉轉烤雞", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["goldmeal"] = {"chinese_name": "富饒塔瑪利玉米粽", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["t13meal"] = {"chinese_name": "什錦飯鍋", "crafting_upgrade": 5, "ascension_upgrade": 0}
# blueprints["firecrabmeal"] = {"chinese_name": "極熱火鍋", "crafting_upgrade": 5, "ascension_upgrade": 0}

blueprints["ember"] = {"chinese_name": "餘燼元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["flaming"] = {"chinese_name": "火焰元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["blaze"] = {"chinese_name": "烈火元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["inferno"] = {"chinese_name": "地獄元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["bubble"] = {"chinese_name": "泡泡元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["tidal"] = {"chinese_name": "潮汐元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["flood"] = {"chinese_name": "洪水元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["torrent"] = {"chinese_name": "奔流元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["breeze"] = {"chinese_name": "微風元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["gale"] = {"chinese_name": "疾風元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["tempest"] = {"chinese_name": "暴風元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hurricane"] = {"chinese_name": "颶風元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["natural"] = {"chinese_name": "自然元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["wild"] = {"chinese_name": "野性元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["primal"] = {"chinese_name": "原始元素", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["primeval"] = {"chinese_name": "太初元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["light"] = {"chinese_name": "光元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["holy"] = {"chinese_name": "聖潔元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["sacred"] = {"chinese_name": "神聖元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["divine"] = {"chinese_name": "神性元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["corrupted"] = {"chinese_name": "腐朽元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["unholy"] = {"chinese_name": "褻瀆元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["nightmare"] = {"chinese_name": "夢魘元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["abyssal"] = {"chinese_name": "深淵元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["luxuriouselement"] = {"chinese_name": "豪華元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["opulentelement"] = {"chinese_name": "富饒元素", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["turtle"] = {"chinese_name": "公羊靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["wolf"] = {"chinese_name": "野狼靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["ox"] = {"chinese_name": "公牛靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["eagle"] = {"chinese_name": "天鷹靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["viper"] = {"chinese_name": "蝮蛇靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["cat"] = {"chinese_name": "貓之靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["rabbitspirit"] = {"chinese_name": "兔子靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["luxuriousspirit"] = {"chinese_name": "索洛托靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["rhino"] = {"chinese_name": "犀牛靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["owl"] = {"chinese_name": "貓頭鷹靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["armadillo"] = {"chinese_name": "犰狳靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lizard"] = {"chinese_name": "蜥蜴靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["crab"] = {"chinese_name": "馬之靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["hippo"] = {"chinese_name": "河馬靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["shark"] = {"chinese_name": "鯊魚靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["walrus"] = {"chinese_name": "海象靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["lion"] = {"chinese_name": "獅子靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["bear"] = {"chinese_name": "巨熊靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["mammoth"] = {"chinese_name": "毛象靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["dinosaur"] = {"chinese_name": "恐龍靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["tiger"] = {"chinese_name": "老虎靈體", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["opulentspirit"] = {"chinese_name": "羽蛇神靈體", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["phoenix"] = {"chinese_name": "鳳凰靈體", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["hydra"] = {"chinese_name": "九頭蛇靈體", "crafting_upgrade": 0, "ascension_upgrade": 0}
blueprints["tarrasque"] = {"chinese_name": "泰拉斯奎靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["carbuncle"] = {"chinese_name": "紅寶石獸靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["chimera"] = {"chinese_name": "奇美拉靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}
blueprints["kraken"] = {"chinese_name": "海怪克拉肯靈體", "crafting_upgrade": 0, "ascension_upgrade": 0}
# blueprints["santa"] = {"chinese_name": "聖誕靈體", "crafting_upgrade": 5, "ascension_upgrade": 0}